Repository bothub-it/bothub-nlp, pull requests merged in 2019-11, with the labels that each got.

#160 Added analyze char
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
Labels: enhancement

#161 Update to New Rasa 1.4.3
  bothub-nlp-api/Pipfile
  bothub-nlp-api/Pipfile.lock
  bothub-nlp-nlu-worker-on-demand/Pipfile
  bothub-nlp-nlu-worker-on-demand/Pipfile.lock
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/__init__.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/evaluate.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/persistor.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/crf_label_as_entity_extractor.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/optimized_spacy_nlp_with_labels.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/regex_featurizer_with_labels.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/tokenizer_spacy_with_labels.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/rasa_utils.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
  bothub-nlp-nlu-worker/requirements.txt
Labels: enhancement

#162 Updated API to FastAPI + Swagger Doc with Unicorn + Gunicorn Optimized
  bothub-nlp-api/Pipfile
  bothub-nlp-api/Pipfile.lock
  bothub-nlp-api/README.md
  bothub-nlp-api/bothub_nlp_api/app.py
  bothub-nlp-api/bothub_nlp_api/handlers/evaluate.py
  bothub-nlp-api/bothub_nlp_api/handlers/parse.py
  bothub-nlp-api/bothub_nlp_api/handlers/train.py
  bothub-nlp-api/bothub_nlp_api/models.py
  bothub-nlp-api/bothub_nlp_api/routers.py
  bothub-nlp-api/bothub_nlp_api/routers/__init__.py
  bothub-nlp-api/bothub_nlp_api/routers/v1.py
  bothub-nlp-api/bothub_nlp_api/routers/v2.py
  bothub-nlp-api/bothub_nlp_api/settings.py
  bothub-nlp-api/bothub_nlp_api/utils.py
  bothub-nlp-api/bothub_nlp_api/wsgi.py
  bothub-nlp-api/entrypoint.sh
  bothub-nlp-api/gunicorn.conf.py
  bothub-nlp-api/main.py
Labels: enhancement

#163 Updated Evaluate to New Version
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/evaluate.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/regex_featurizer_with_labels.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/rasa_utils.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
Labels: bug

#164 [fix] Parse
  bothub-nlp-api/bothub_nlp_api/models.py
Labels: bug

#165 Added router pagination
  bothub-nlp-api/Pipfile
  bothub-nlp-api/Pipfile.lock
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub-nlp-nlu-worker/requirements.txt
Labels: enhancement

#168 [fix] API Info NLP
  bothub-nlp-api/bothub_nlp_api/models.py
  bothub-nlp-api/bothub_nlp_api/routers/v1.py
  bothub-nlp-api/bothub_nlp_api/routers/v2.py
Labels: bug

#172 Develop
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/count_vectors_featurizer_no_lemmatize.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
Labels: enhancement

#173 Ignore Accents
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
Labels: bug, enhancement

#175 Download Train from AWS
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/persistor.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/count_vectors_featurizer_no_lemmatize.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
Labels: enhancement

#180 Staging
  bothub-nlp-api/Pipfile
  bothub-nlp-api/Pipfile.lock
  bothub-nlp-api/README.md
  bothub-nlp-api/bothub_nlp_api/__init__.py
  bothub-nlp-api/bothub_nlp_api/app.py
  bothub-nlp-api/bothub_nlp_api/settings.py
  bothub-nlp-nlu-worker-on-demand/Pipfile
  bothub-nlp-nlu-worker-on-demand/Pipfile.lock
  bothub-nlp-nlu-worker-on-demand/bothub_nlp_nlu_worker_on_demand/__init__.py
  bothub-nlp-nlu-worker/README.md
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/__init__.py
  bothub-nlp-nlu-worker/bothub_nlp_nlu_worker/bothub_nlp_nlu/__init__.py
  bothub-nlp-nlu-worker/requirements.txt
Labels: enhancement
