Repository bothub-it/bothub-nlp, pull requests merged in 2020-05, with the labels that each got.

#203 Add algorithm to remove repeated words
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/preprocessing.py
  requirements.txt
Labels: enhancement

#206 Refact router examples get labels and entities
  bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/words_distribution.py
  requirements.txt
Labels: bug, enhancement

#211 Add new models and update rasa to 1.10
  Makefile
  bothub_nlp_nlu_worker/bothub_nlp_nlu/__init__.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/evaluate.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/parse.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/count_vectors_featurizer_no_lemmatize.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/crf_label_as_entity_extractor.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/embedding_intent_classifier.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/optimized_spacy_nlp_with_labels.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/preprocessing.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/regex_featurizer_with_labels.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/pipeline_components/tokenizer_spacy_with_labels.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
  bothub_nlp_nlu_worker/tests/celery_app.py
  requirements.txt
Labels: enhancement, help wanted

#219 Submit rasa version to the engine
  bothub_nlp_nlu_worker/bothub_nlp_nlu/debug_parse.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/evaluate.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/parse.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/persistor.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/train.py
  bothub_nlp_nlu_worker/bothub_nlp_nlu/utils.py
  requirements.txt
  requirements_dev.txt
Labels: enhancement
